import { useContext, useEffect } from 'react';
import { DollarContext } from './context/DollarContext';
import { ContextInt } from './interfaces/context_interfaces';
import { getDollarValues } from './api/dolar-hoy';
import { DollarValues } from './interfaces/dollar_interfaces';
import { QuoteForm } from './components/QuoteForm';
import { QuotationHistory } from './components/QuotationHistory';

function App() {
    const { dispatch } = useContext(DollarContext) as ContextInt;

    useEffect(() => {
        getDollarValues().then((response) => {
            const payload: DollarValues = {
                officialDollar: response.official,
                blueDollar: response.blue,
                cclDollar: response.ccl,
                mepDollar: response.mep,
            };
            dispatch({
                type: 'FILL_DOLLAR_VALUES',
                payload,
            });
        });
    }, [dispatch]);

    return (
        <div className='container mt-3'>
            <h1>Calculadora</h1>
            <main className="row">
                <section className='col-md-8'>
                    <QuoteForm />
                </section>
                <aside className='col-md-4'>
                    <QuotationHistory/>
                </aside>
            </main>
        </div> // Generated by https://quicktype.io
    );
}

export default App;
